### ISSUE TITLE
Error when running the patcher

### ISSUE THREAD

**Issue by saberthesword** [focustense/FocusPatchers#1]
Here's the log for that session
[log-20210625.txt](https://github.com/focustense/FocusPatchers/files/6711189/log-20210625.txt)

**Comment by focustense** [comment]
Seems to be choking on the bashed patch:

```
[295.1][FocusPatchers] Checking mod: Bashed Patch, 0
[295.3][FocusPatchers] RecordException Null => Null<Race>: Could not resolve record    at Mutagen.Bethesda.IFormLinkExt.Resolve[TMajor](IFormLinkGetter`1 link, ILinkCache cache)
[295.3][FocusPatchers]    at RespectMyBodySlide.Program.PatchNpc(INpcGetter npc, IReadOnlySet`1 implicits, IPatcherState`2 state) in C:\Users\user\AppData\Local\Temp\Synthesis\4042b6c3-7a47-47d6-a113-09e99ea79604\Git\b5hhpfiu.wnt\Runner\RespectMyBodySlide\Program.cs:line 59
[295.3][FocusPatchers]    at RespectMyBodySlide.Program.RunPatch(IPatcherState`2 state) in C:\Users\user\AppData\Local\Temp\Synthesis\4042b6c3-7a47-47d6-a113-09e99ea79604\Git\b5hhpfiu.wnt\Runner\RespectMyBodySlide\Program.cs:line 45
[295.3][FocusPatchers]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass12_0`2.<<AddPatch>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 93
[295.3][FocusPatchers] --- End of stack trace from previous location ---
[295.3][FocusPatchers]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, ModKey exportKey) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 455
[295.3][FocusPatchers]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 403
[295.3][FocusPatchers]    at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 377
```

Apparently there's an NPC without a race? That seems very weird to me, because I don't think race is optional. In Mutagen it's an `IFormLinkGetter` rather than an `IFormLinkNullableGetter`, yet apparently it is null here.

It's a 1-line workaround, but I recommend you also take a closer look at your bashed patch because there is something in there that shouldn't be in there.
